version: 2
executorType: machine
jobs:
  build:
    working_directory: ~/source
    docker:
    machine:
      image: circleci/docker
    steps:
      - checkout
      - run: docker run --env gh_token=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 --env gh_user=smillxx --env gh_email=smillerd82@gmail.com --env gh_repo=soc2-policy-templates