version: 2
executorType: machine
jobs:
  build:
    working_directory: ~/source
    docker:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: docker run --env gh_token=${GH_TOKEN} --env gh_user=smillxx --env gh_email=smillerd82@gmail.com --env gh_repo=soc2-policy-templates