version: 2
executorType: machine
jobs:
  build:
    working_directory: ~/source
    docker:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: docker run --env gh_token=${GITHUB_TOKEN} --env gh_user=${GITHUB_USER} --env gh_email=${GITHUB_EMAIL} --env gh_repo=${GITHUB_REPO} ${COMPLY_APP_IMAGE}
